export const districts = [
    {
        name:"All Districts",
        to:"/districts/alldistricts"
    },
    {
        name:"Ariyalur",
        to:"/districts/ariyalur"
    },
   
    {
        name:"Chengalpattu",
        to:"/districts/chengalpattu"
    },
    {
        name:"Chennai",
        to:"/districts/chennai"
    },
    {
        name:"Coimabatore",
        to:"/districts/coimabatore"
    },
    {
        name:"Dharmapuri",
        to:"/districts/dharmapuri"
    },
    {
        name:"Dindugal",
        to:"/districts/dindugal"
    },
    {
        name:"Erode",
        to:"/districts/erode"
    },
    {
        name:"Kallakurichi",
        to:"/districts/kallakurichi"
    },
    {
        name:"Kanchipuram",
        to:"/districts/kanchipuram"
    },

    {
        name:"Kanyakuamri",
        to:"/districts/kanyakuamri"
    },
    {
        name:"Karur",
        to:"/districts/karur"
    },
    {
        name:"Krishnagiri",
        to:"/districts/krishnagiri"
    }, {
        name:"Madurai",
        to:"/districts/madurai"
    },
    {
        name:"Mayiladurai",
        to:"/districts/mayiladurai"
    },
    {
        name:"Nagapattinam",
        to:"/districts/nagapattinam"
    },
    {
        name:"Nilgirs",
        to:"/districts/nilgirs"
    },
    {
        name:"Namakkal",
        to:"/districts/namakkal"
    },
    {
        name:"Perambalur",
        to:"/districts/perambalur"
    },
    {
        name:"Pudukottai",
        to:"/districts/pudukottai"
    },
    {
        name:"Ramanathapuram",
        to:"/districts/ramanathapuram"
    },
    {
        name:"Ranipet",
        to:"/districts/ranipet"
    },
    {
        name:"Salem",
        to:"/districts/salem"
    },
    {
        name:"Sivagangai",
        to:"/districts/sivagangai"
    },
    {
        name:"Tenkasi",
        to:"/districts/tenkasi"
    },
    {
        name:"Thiruvallur",
        to:"/districts/thiruvallur"
    },
    {
        name:"Thanjavur",
        to:"/districts/thanjavur "
    },
    {
        name:"Thiruvarur",
        to:"/districts/thiruvarur"
    },
    {
        name:"Tuticorn",
        to:"/districts/tuticorn"
    },
    {
        name:"Trichirappalli",
        to:"/districts/trichirappalli"
    },
    {
        name:"Thirunelvelli",
        to:"/districts/thirunelvelli"
    },
    {
        name:"Tirupathur",
        to:"/districts/tirupathur"
    },
    {
        name:"Tiruppur",
        to:"/districts/tiruppur"
    },
    {
        name:"Vellore",
        to:"/districts/vellore"
    },
    {
        name:"Vilupuram",
        to:"/districts/vilupuram"
    },
    {
        name:"Virudhunagar",
        to:"/districts/virudhunagar"
    }
]